### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function setData() on bool

### ISSUE THREAD

**Issue by kanevbg** [magenizr/Magenizr_ResetUiBookmarks#7]
```
Fatal error: Uncaught Error: Call to a member function setData() on bool in vendor/magenizr/magento2-resetuibookmarks/Plugin/Block/Adminhtml/User/Edit/Tab/ResetUiBookmarks.php:40 Stack trace:
#0 vendor/magento/framework/Interception/Interceptor.php(135): Magenizr\ResetUiBookmarks\Plugin\Block\Adminhtml\User\Edit\Tab\ResetUiBookmarks->aroundGetFormHtml(Object(Magento\User\Block\User\Edit\Tab\Main\Interceptor), Object(Closure))
#1 vendor/magento/framework/Interception/Interceptor.php(153): Magento\User\Block\User\Edit\Tab\Main\Interceptor->Magento\Framework\Interception\{closure}()
#2 generated/code/Magento/User/Block/User/Edit/Tab/Main/Interceptor.php(39): Magento\User\Block\User\Edit\Tab\Main\Interceptor->___callPlugins('getFormHtml', Array, NULL)
#3 vendor/magento/module-backend/view/adminhtml/templates/widget/form.phtml(13): Magento\User\Block\User\Edit\Tab\Main\Interceptor->getFormHtml()
#4 vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/opt/www/projec...')
#5 vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\User\Block\User\Edit\Tab\Main\Interceptor), '/opt/www/projec...', Array)
#6 generated/code/Magento/User/Block/User/Edit/Tab/Main/Interceptor.php(258): Magento\Framework\View\Element\Template->fetchView('/opt/www/projec...')
#7 vendor/magento/framework/View/Element/Template.php(301): Magento\User\Block\User\Edit\Tab\Main\Interceptor->fetchView('/opt/www/projec...')
#8 vendor/magento/module-backend/Block/Template.php(129): Magento\Framework\View\Element\Template->_toHtml()
#9 vendor/magento/framework/View/Element/AbstractBlock.php(1100): Magento\Backend\Block\Template->_toHtml()
#10 vendor/magento/framework/View/Element/AbstractBlock.php(1104): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#11 vendor/magento/framework/View/Element/AbstractBlock.php(674): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#12 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\AbstractBlock->toHtml()
#13 vendor/magento/framework/Interception/Interceptor.php(138): Magento\User\Block\User\Edit\Tab\Main\Interceptor->___callParent('toHtml', Array)
#14 app/code/HD/FPC/Plugin/View/Element/AbstractBlockPlugin.php(77): Magento\User\Block\User\Edit\Tab\Main\Interceptor->Magento\Framework\Interception\{closure}()
#15 vendor/magento/framework/Interception/Interceptor.php(135): HD\FPC\Plugin\View\Element\AbstractBlockPlugin->aroundToHtml(Object(Magento\User\Block\User\Edit\Tab\Main\Interceptor), Object(Closure))
#16 vendor/magento/framework/Interception/Interceptor.php(153): Magento\User\Block\User\Edit\Tab\Main\Interceptor->Magento\Framework\Interception\{closure}()
#17 generated/code/Magento/User/Block/User/Edit/Tab/Main/Interceptor.php(585): Magento\User\Block\User\Edit\Tab\Main\Interceptor->___callPlugins('toHtml', Array, NULL)
#18 vendor/magento/module-user/Block/User/Edit/Tabs.php(40): Magento\User\Block\User\Edit\Tab\Main\Interceptor->toHtml()
#19 vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\User\Block\User\Edit\Tabs->_beforeToHtml()
#20 vendor/magento/framework/View/Element/AbstractBlock.php(1104): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#21 vendor/magento/framework/View/Element/AbstractBlock.php(674): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#22 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\AbstractBlock->toHtml()
#23 vendor/magento/framework/Interception/Interceptor.php(138): Magento\User\Block\User\Edit\Tabs\Interceptor->___callParent('toHtml', Array)
#24 app/code/HD/FPC/Plugin/View/Element/AbstractBlockPlugin.php(77): Magento\User\Block\User\Edit\Tabs\Interceptor->Magento\Framework\Interception\{closure}()
#25 vendor/magento/framework/Interception/Interceptor.php(135): HD\FPC\Plugin\View\Element\AbstractBlockPlugin->aroundToHtml(Object(Magento\User\Block\User\Edit\Tabs\Interceptor), Object(Closure))
#26 vendor/magento/framework/Interception/Interceptor.php(153): Magento\User\Block\User\Edit\Tabs\Interceptor->Magento\Framework\Interception\{closure}()
#27 generated/code/Magento/User/Block/User/Edit/Tabs/Interceptor.php(806): Magento\User\Block\User\Edit\Tabs\Interceptor->___callPlugins('toHtml', Array, Array)
#28 vendor/magento/framework/View/Layout.php(579): Magento\User\Block\User\Edit\Tabs\Interceptor->toHtml()
#29 vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock('adminhtml.user....')
#30 generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('adminhtml.user....')
#31 vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('adminhtml.user....')
#32 generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('adminhtml.user....', false)
#33 vendor/magento/framework/View/Layout.php(607): Magento\Framework\View\Layout\Interceptor->renderElement('adminhtml.user....', false)
#34 vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('left', false)
#35 generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('left')
#36 vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('left')
#37 generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('left', false)
#38 vendor/magento/framework/View/Layout.php(607): Magento\Framework\View\Layout\Interceptor->renderElement('left', false)
#39 vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('side.col', false)
#40 generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('side.col')
#41 vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('side.col')
#42 generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('side.col', false)
#43 vendor/magento/framework/View/Layout.php(607): Magento\Framework\View\Layout\Interceptor->renderElement('side.col', false)
#44 vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.main.conta...', false)
#45 generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#46 vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#47 generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', false)
#48 vendor/magento/framework/View/Layout.php(607): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...', false)
#49 vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.content', false)
#50 generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#51 vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#52 generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', false)
#53 vendor/magento/framework/View/Layout.php(607): Magento\Framework\View\Layout\Interceptor->renderElement('page.content', false)
#54 vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#55 generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#56 vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#57 generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#58 vendor/magento/framework/View/Layout.php(607): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false)
#59 vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('backend.page', false)
#60 generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#61 vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#62 generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', false)
#63 vendor/magento/framework/View/Layout.php(607): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page', false)
#64 vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('root', false)
#65 generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#66 vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#67 generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#68 vendor/magento/framework/View/Layout.php(976): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#69 generated/code/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#70 vendor/magento/framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput()
#71 vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#72 generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#73 vendor/magento/framework/App/View.php(221): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#74 vendor/magento/module-user/Controller/Adminhtml/User/Edit.php(49): Magento\Framework\App\View->renderLayout()
#75 generated/code/Magento/User/Controller/Adminhtml/User/Edit/Interceptor.php(24): Magento\User\Controller\Adminhtml\User\Edit->execute()
#76 vendor/magento/framework/App/Action/Action.php(108): Magento\User\Controller\Adminhtml\User\Edit\Interceptor->execute()
#77 vendor/magento/module-backend/App/AbstractAction.php(248): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#78 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#79 vendor/magento/framework/Interception/Interceptor.php(138): Magento\User\Controller\Adminhtml\User\Edit\Interceptor->___callParent('dispatch', Array)
#80 vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\User\Controller\Adminhtml\User\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#81 vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\User\Controller\Adminhtml\User\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#82 vendor/magento/framework/Interception/Interceptor.php(153): Magento\User\Controller\Adminhtml\User\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#83 generated/code/Magento/User/Controller/Adminhtml/User/Edit/Interceptor.php(39): Magento\User\Controller\Adminhtml\User\Edit\Interceptor->___callPlugins('dispatch', Array, NULL)
#84 vendor/magento/framework/App/FrontController.php(186): Magento\User\Controller\Adminhtml\User\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#85 vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\User\Controller\Adminhtml\User\Edit\Interceptor))
#86 vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#87 vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#88 vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#89 generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#90 vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#91 vendor/magento/framework/App/Bootstrap.php(261): Magento\Framework\App\Http->launch()
#92 pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#93 {main} thrown in vendor/magenizr/magento2-resetuibookmarks/Plugin/Block/Adminhtml/User/Edit/Tab/ResetUiBookmarks.php on line 40
```
this exception is throw when opening admin user from the admin panel.

**Comment by magenizr** [comment]
Hi @kanevbg 

Thanks for raising the issue. I am happy to look at this, jus two questions:
- What Magento version are you on?
- Do you have another 3rd party module installed that overrides `<block class="Magento\User\Block\User\Edit\Tabs" name="adminhtml.user.edit.tabs">`?

**Comment by kanevbg** [comment]
@magenizr 2.3.7-p2

**Comment by magenizr** [comment]
Thanks @kanevbg I'll have a look and come back to you asap.

**Comment by magenizr** [comment]
Hi @kanevbg 

You probably have to downgrade to 1.1.0 which is the last stable version of ResetUiBookmarks before the 2.4.x compatibility update which will conflict with the escaper in 2.3.7.

```
composer require "magenizr/magento2-resetuibookmarks":"1.1.0" --no-update
composer update "magenizr/magento2-resetuibookmarks" --no-install
composer install
Package operations: 0 installs, 1 update, 0 removals
  - Downloading magenizr/magento2-resetuibookmarks (1.1.0)
  - Downgrading magenizr/magento2-resetuibookmarks (1.2.0 => 1.1.0): Extracting archive
```

![screencapture-app-issue-test-backend-admin-system-account-index-key-12ebe9995b2ec760c7b312c10fc01d9865b93f68d7cbc58ad4ab3db0f16f816b-2023-03-28-21_25_01](https://user-images.githubusercontent.com/36174840/228208283-e50153b3-41b4-43bb-9188-23b577f76994.png)

Let me know how you go with that. Otherwise, I can see another module in your log output `app/code/HD/FPC/Plugin/View/Element/AbstractBlockPlugin.php` which is probably conflicting. Can you email me a copy of that file to support@magenizr.com?

**Comment by magenizr** [comment]
Hi @kanevbg 

Just checking if you were able to test this again without the plugin  `app/code/HD/FPC/Plugin/View/Element/AbstractBlockPlugin.php`?

**Comment by kanevbg** [comment]
Hi,

I reverted the version right after posting the issue, but I hope that we can solve the issue in order for Magento 2.3.7-p* to be supported in newest versions too?

**Comment by magenizr** [comment]
Hi @kanevbg 

Can you please let me know again what version of ResetUiBookmarks you are trying to install on 2.3.7-p*? When I install ResetUiBookmarks 1.2.1 I get a different error, which is related to a theme standard that is required in 2.4.x.

Exception #0 (Exception): Notice: Undefined variable: escaper in /var/www/html/vendor/magenizr/magento2-resetuibookmarks/view/adminhtml/templates/system/account/resetuibookmarks.phtml on line 14

Also, can you please past the content of your `app/code/HD/FPC/Plugin/View/Element/AbstractBlockPlugin.php` or email us [support@magenizr.com](mailto:support@magenizr.com) so that I can provide you a solution.

**Comment by magenizr** [comment]
Hi @kanevbg 

I am going to close this issue for now. Feel free to reach out by email or create a ticket via https://account.magenizr.com so that we can discuss the potential conflict with your plugin further.
